"""Fix ChatroomMember mission_id foreign key

Revision ID: 1cc7d4d327fa
Revises: 307293ddcfda
Create Date: 2025-05-12 16:06:38.694294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc7d4d327fa'
down_revision = '307293ddcfda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatroom_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mission_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chatroommembber_mission_id', 'mission', ['mission_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatroom_member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mission_id')

    # ### end Alembic commands ###
