"""Add mission_id with named constraint

Revision ID: 307293ddcfda
Revises: dad28f2f2f53
Create Date: 2025-05-12 15:46:59.869603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307293ddcfda'
down_revision = 'dad28f2f2f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mission_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chatroom_mission_id', 'mission', ['mission_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatroom', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chatroom_mission_id', type_='foreignkey')
        batch_op.drop_column('mission_id')

    # ### end Alembic commands ###
