"""Add is_verified to ChatroomMember

Revision ID: 47e5b76a4de4
Revises: 48822c654264
Create Date: 2025-05-05 12:01:02.264674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e5b76a4de4'
down_revision = '48822c654264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatroom_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatroom_member', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
