"""Added roles and verification to ChatroomMember

Revision ID: dad28f2f2f53
Revises: 47e5b76a4de4
Create Date: 2025-05-12 13:11:08.045187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad28f2f2f53'
down_revision = '47e5b76a4de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatroom_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatroom_member', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
